### PR TITLE
Exclude node modules

### LINKED ISSUE #3: Cs fix tryes to fix node_modules
## Describe the bug

CS fixer tryes to fix files in `node_modules` directory.

### Steps to reproduce the behavior:

- Install any deps whith php file inside (ex. `navigo` module)
- run CS-Fixer

## System information

Any

### PR DESCRIPTION
**Pull request by jetexe**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No

## Description

Added folder `node_modules` to .

Fixes #3

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code
- [x] I have made changes in [CHANGELOG.md](https://github.com/avto-dev/php-cs-fixer/blob/master/CHANGELOG.md) file

### CODE REVIEW

File: cs_excludes.php [hunk 1]
```diff
@@ -11,4 +11,5 @@
     'vendor',
     'public',
     'resources',
+    'node-modules',
```
Comment (tarampampam) [inline cs_excludes.php]: Not `node_modules`?

**Review by tarampampam — CHANGES_REQUESTED** [review]

File: cs_excludes.php (hunk 1 above)
Comment (jetexe) [reply cs_excludes.php]: Fixed

**Review by tarampampam — APPROVED** [review]
